version: "3"

services:
  creatadnode0:
    container_name: creatadnode0
    image: "creatasdk/creatad-env"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-creatad.log}
    volumes:
      - ./build:/creatad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  creatadnode1:
    container_name: creatadnode1
    image: "creatasdk/creatad-env"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-creatad.log}
    volumes:
      - ./build:/creatad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  creatadnode2:
    container_name: creatadnode2
    image: "creatasdk/creatad-env"
    environment:
      - ID=2
      - LOG=${LOG:-creatad.log}
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ./build:/creatad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  creatadnode3:
    container_name: creatadnode3
    image: "creatasdk/creatad-env"
    environment:
      - ID=3
      - LOG=${LOG:-creatad.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ./build:/creatad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
